USE prodction;

CREATE TABLE IF NOT EXISTS job_setting_changes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  old_job_id INT NOT NULL,
  old_shift_id INT NOT NULL,
  machine_id INT NOT NULL,
  operator_id INT NOT NULL,
  new_part_id INT NOT NULL,
  new_component VARCHAR(50) NOT NULL,
  new_drg_no VARCHAR(100) DEFAULT NULL,
  new_operation VARCHAR(150) DEFAULT NULL,
  new_cutter_id INT DEFAULT NULL,
  new_planned_qty INT NOT NULL DEFAULT 0,
  reason VARCHAR(150) NOT NULL,
  remarks VARCHAR(255) DEFAULT NULL,
  total_qty INT NOT NULL DEFAULT 0,
  ok_qty INT NOT NULL DEFAULT 0,
  mc_reject_qty INT NOT NULL DEFAULT 0,
  rm_defect_qty INT NOT NULL DEFAULT 0,
  rework_qty INT NOT NULL DEFAULT 0,
  started_at DATETIME NOT NULL,
  completed_at DATETIME DEFAULT NULL,
  status ENUM('In Progress','Completed') NOT NULL DEFAULT 'In Progress',
  new_job_id INT DEFAULT NULL,
  started_by_user_id INT NOT NULL,
  completed_by_user_id INT DEFAULT NULL,
  active_machine_id INT AS (CASE WHEN status = 'In Progress' THEN machine_id ELSE NULL END) PERSISTENT,
  UNIQUE KEY unique_active_setting_change_per_machine (active_machine_id),
  KEY idx_setting_changes_old_job (old_job_id),
  KEY idx_setting_changes_old_shift (old_shift_id),
  KEY idx_setting_changes_new_job (new_job_id),
  FOREIGN KEY (old_job_id) REFERENCES production_jobs(id),
  FOREIGN KEY (old_shift_id) REFERENCES job_shifts(id),
  FOREIGN KEY (machine_id) REFERENCES machines(id),
  FOREIGN KEY (operator_id) REFERENCES operators(id),
  FOREIGN KEY (new_part_id) REFERENCES parts(id),
  FOREIGN KEY (new_cutter_id) REFERENCES cutters(id),
  FOREIGN KEY (new_job_id) REFERENCES production_jobs(id),
  FOREIGN KEY (started_by_user_id) REFERENCES users(id),
  FOREIGN KEY (completed_by_user_id) REFERENCES users(id)
);
