CREATE TABLE IF NOT EXISTS job_cutter_changes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  job_id INT NOT NULL,
  shift_id INT NOT NULL,
  old_cutter_id INT DEFAULT NULL,
  new_cutter_id INT NOT NULL,
  reason VARCHAR(150) NOT NULL,
  remarks VARCHAR(255) DEFAULT NULL,
  started_at DATETIME NOT NULL,
  completed_at DATETIME DEFAULT NULL,
  status ENUM('In Progress','Completed') NOT NULL DEFAULT 'In Progress',
  started_by_user_id INT NOT NULL,
  completed_by_user_id INT DEFAULT NULL,
  active_job_id INT AS (CASE WHEN status = 'In Progress' THEN job_id ELSE NULL END) PERSISTENT,
  UNIQUE KEY unique_active_cutter_change_per_job (active_job_id),
  KEY idx_cutter_changes_job (job_id),
  KEY idx_cutter_changes_shift (shift_id),
  FOREIGN KEY (job_id) REFERENCES production_jobs(id),
  FOREIGN KEY (shift_id) REFERENCES job_shifts(id),
  FOREIGN KEY (old_cutter_id) REFERENCES cutters(id),
  FOREIGN KEY (new_cutter_id) REFERENCES cutters(id),
  FOREIGN KEY (started_by_user_id) REFERENCES users(id),
  FOREIGN KEY (completed_by_user_id) REFERENCES users(id)
);
